### ISSUE TITLE
support existing volume claims

### ISSUE THREAD

**Issue by brunnels** [adambkaplan/plex-operator#10]
I have several nfs exports from my NAS that I already have volume claims configured for.  Can you add support configure the volumes and volumeMounts for the data persistence?

```
volumes:
  - name: pvc-movies
    persistentVolumeClaim:
      claimName: pvc-movies
  - name: pvc-tv
    persistentVolumeClaim:
      claimName: pvc-tv
  - name: pvc-music
    persistentVolumeClaim:
      claimName: pvc-music
  - name: pvc-pictures
    persistentVolumeClaim:
      claimName: pvc-pictures

volumeMounts:
  - name: pvc-movies
    mountPath: "/data/movies"
  - name: pvc-tv
    mountPath: "/data/tv"
  - name: pvc-music
    mountPath: "/data/music"
  - name: pvc-pictures
    mountPath: "/data/pictures"
```
