### ISSUE TITLE
gpu transcoding support and resource limits

### ISSUE THREAD

**Issue by brunnels** [adambkaplan/plex-operator#9]
Where can I set container environment variables and resource limits to run the pod only on nodes that support hardware transcoding?

For instance with this chart https://github.com/k8s-at-home/charts/blob/master/charts/stable/plex/values.yaml
I would have values.yml be something like this:
```
env:
  TZ: "America/Chicago"
  PLEX_CLAIM: "claim$$$$$$"
  PLEX_PREFERENCE_1: "FriendlyName=plex-k3s"
  PLEX_PREFERENCE_2: "EnableIPv6=0"
resources:
  limits:
    nvidia.com/gpu.present: true
```
